In [1]:
import numpy as np

In [7]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
ones = np.ones((2, 3), dtype = int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
random = np.random.random((2, 3))
random

array([[0.58262828, 0.20647159, 0.74695571],
       [0.19861028, 0.75954586, 0.37704879]])

In [11]:
mu, sigma = 2, 0.5
v = np.random.normal(mu, sigma, 100)
v

array([1.78878508, 1.816818  , 1.61293247, 1.66858931, 1.28441195,
       2.23776366, 2.15279842, 1.24606812, 2.33380213, 2.35140355,
       1.73200306, 2.05520935, 1.95691191, 2.01325504, 2.21163199,
       2.10072485, 1.83291001, 2.00668282, 1.59541531, 1.68783018,
       2.3494818 , 1.61423296, 1.72945457, 2.14707474, 1.08107976,
       2.39173714, 2.44098944, 1.37862298, 1.95680773, 1.41094607,
       2.39402097, 3.7823712 , 2.80589276, 1.78884603, 2.14557369,
       1.95556952, 1.71206906, 2.41619079, 2.54894907, 1.7860213 ,
       1.25220877, 2.17312181, 1.37371953, 1.63836286, 2.34879722,
       1.07356886, 2.01363928, 1.9452094 , 1.08025727, 1.11550783,
       2.12653996, 2.32404056, 2.12018597, 2.41508389, 2.42617132,
       0.97540579, 2.31022009, 2.01746917, 1.60543987, 1.06059204,
       2.85982395, 2.24118199, 1.28158603, 1.49731999, 1.84048835,
       2.28111714, 1.15225573, 2.74395454, 1.8298101 , 1.22404752,
       2.10944455, 1.464805  , 1.79076647, 1.58073754, 1.98687

In [12]:
arr.ndim

2

In [13]:
random.ndim

2

In [14]:
v.ndim

1

In [15]:
arr.shape

(3, 3)

In [16]:
arr.size

9

In [17]:
arr.dtype.name

'int32'

In [18]:
a = np.array([6, 5, 4, 8])
b = np.array([1, 2, 5, 10])
a - b

array([ 5,  3, -1, -2])

In [19]:
a + b

array([ 7,  7,  9, 18])

In [20]:
a * b

array([ 6, 10, 20, 80])

In [22]:
b ** 2

array([  1,   4,  25, 100], dtype=int32)

In [23]:
np.sin(b)

array([ 0.84147098,  0.90929743, -0.95892427, -0.54402111])

In [24]:
b > 1

array([False,  True,  True,  True])

In [26]:
values = [5, 2, 1, 1, 6, 2, 0, 1]
np.unique(values)

array([0, 1, 2, 5, 6])

In [27]:
arr.sum(axis = 0)

array([ 9, 12, 15])

In [28]:
arr.sum(axis = 1)

array([ 3, 12, 21])

In [29]:
arr.min(axis = 1)

array([0, 3, 6])

In [30]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [32]:
arr.cumsum(axis = 1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [33]:
np.floor([0.5, 1.1, -1.2, 5, -2.0])

array([ 0.,  1., -2.,  5., -2.])

In [56]:
a = np.array([[3, 4 ,5], [7, 8, 3], [0, 3, 23], [8, 11 ,6]])
a

array([[ 3,  4,  5],
       [ 7,  8,  3],
       [ 0,  3, 23],
       [ 8, 11,  6]])

In [36]:
a.shape

(4, 3)

In [37]:
a[1, 1]

8

In [38]:
a[3, 2]

6

In [39]:
a[3, 3]  # IndexError: index 3 is out of bounds for axis 1 with size 3

IndexError: index 3 is out of bounds for axis 1 with size 3

In [40]:
a[0, 0:2]

array([3, 4])

In [42]:
a[3, 0:3]

array([ 8, 11,  6])

In [43]:
a[1, :]

array([7, 8, 3])

In [46]:
a[ :, 1 ]

array([ 4,  8,  3, 11])

In [45]:
a[ :, -1]

array([ 5,  3, 23,  6])

In [48]:
print(np.arange(5))

[0 1 2 3 4]


In [49]:
y = [1, 1, 2, 2, 1, 1, 3]

In [50]:
for index, item in enumerate(np.unique(y)):
    print(index, item + 1)

0 2
1 3
2 4


In [51]:
for index, item in enumerate(np.arange(len(y))):
    print(index, item + 1)

0 1
1 2
2 3
3 4
4 5
5 6
6 7


In [52]:
a

array([[ 3,  4,  5],
       [ 7,  8,  3],
       [ 0,  3, 23],
       [ 8, 11,  6]])

In [57]:
a.shape

(4, 3)

In [53]:
a.ravel()

array([ 3,  4,  5,  7,  8,  3,  0,  3, 23,  8, 11,  6])

In [58]:
a.shape = (6, 2)
a

array([[ 3,  4],
       [ 5,  7],
       [ 8,  3],
       [ 0,  3],
       [23,  8],
       [11,  6]])

In [60]:
a.transpose()

array([[ 3,  5,  8,  0, 23, 11],
       [ 4,  7,  3,  3,  8,  6]])

In [61]:
a.T.shape

(2, 6)

In [62]:
a.reshape(4, 3)

array([[ 3,  4,  5],
       [ 7,  8,  3],
       [ 0,  3, 23],
       [ 8, 11,  6]])

In [64]:
x1 = np.array([1, 2, 3, 4, 5])
x1_new = x1[ :, np.newaxis]
x1_new 

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [65]:
x1_new.shape

(5, 1)

In [66]:
x2 = np.array([5, 4, 3])
x3 = x1_new + x2
x3

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])

In [67]:
x3_new = x3[:, np.newaxis, 1]
x3_new

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [68]:
x4_new = x3[:, np.newaxis, 2]
x4_new

array([[4],
       [5],
       [6],
       [7],
       [8]])

In [73]:
c = np.array(10 * np.random.random(2, 2)) #TypeError: random_sample() takes at most 1 positional argument (2 given)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [75]:
c = np.floor(10 * np.random.random((2, 2)))
c

array([[5., 2.],
       [7., 5.]])

In [76]:
d = np.floor(10 * np.random.random((2, 2)))
d

array([[1., 6.],
       [2., 3.]])

In [77]:
np.vstack((c, d))

array([[5., 2.],
       [7., 5.],
       [1., 6.],
       [2., 3.]])

In [78]:
np.hstack((c, d))

array([[5., 2., 1., 6.],
       [7., 5., 2., 3.]])

In [79]:
hs = np.floor(10 * np.random.random((2, 12)))
hs

array([[0., 9., 0., 1., 7., 6., 4., 2., 2., 5., 9., 6.],
       [4., 5., 9., 7., 1., 9., 6., 9., 8., 1., 6., 5.]])

In [80]:
hsp = np.hsplit(hs, 3)
hsp

[array([[0., 9., 0., 1.],
        [4., 5., 9., 7.]]), array([[7., 6., 4., 2.],
        [1., 9., 6., 9.]]), array([[2., 5., 9., 6.],
        [8., 1., 6., 5.]])]

In [81]:
hsp[1]

array([[7., 6., 4., 2.],
       [1., 9., 6., 9.]])

In [82]:
vsp = np.vsplit(hs, 2)
vsp

[array([[0., 9., 0., 1., 7., 6., 4., 2., 2., 5., 9., 6.]]),
 array([[4., 5., 9., 7., 1., 9., 6., 9., 8., 1., 6., 5.]])]

In [83]:
la = np.array([[1.0, 2.0],[3.0, 4.0]])
la

array([[1., 2.],
       [3., 4.]])

In [84]:
la.transpose()

array([[1., 3.],
       [2., 4.]])

In [85]:
la.T

array([[1., 3.],
       [2., 4.]])

In [89]:
np.linalg.inv(la)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [90]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [91]:
I1 = np.eye(3)
I1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
M1 = np.array([[1, 2], [0, 1]])
M2 = np.array([[-1, 0], [1, 1]])
M1 * M2

array([[-1,  0],
       [ 0,  1]])

In [93]:
np.dot(M1, M2)

array([[1, 2],
       [1, 1]])

In [95]:
np.trace(I1)

3.0

In [96]:
#Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8
c0 = np.array([[3,1], [1,2]])
c1 = np.array([9,8])
solve = np.linalg.solve(c0, c1)
solve

array([2., 3.])

In [97]:
A = np.mat("3 -2; 1 0")
A

matrix([[ 3, -2],
        [ 1,  0]])

In [98]:
print("Eigenvalues", np.linalg.eigvals(A))

Eigenvalues [2. 1.]
