In [1]:
import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passi

In [2]:
#UPDATE: Note that eager execution is enabled by default in TensorFlow 2.0. So the answer above applies only to TensorFlow 1.x
tf.enable_eager_execution()

In [3]:
tf.constant([
            [[0, 1, 2, 3, 4],
             [5, 6, 7, 8, 9]],
            [[10, 11, 12, 13, 14],
             [15, 16, 17, 18, 19]],
            [[20, 21, 22, 23, 24],
             [25, 26, 27, 28, 29]],])

<tf.Tensor: id=0, shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

In [4]:
tf.constant([[1, 2],
             [3, 4],
             [5, 6]], dtype=tf.float16)

<tf.Tensor: id=2, shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [5]:
tf.constant([
            [[0, 1, 2, 3, 4],
             [5, 6, 7, 8, 9]],
            [[10, 11, 12, 13, 14],
             [15, 16, 17, 18, 19]],
            [[20, 21, 22, 23, 24],
             [25, 26, 27, 28, 29]],])

<tf.Tensor: id=4, shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

In [6]:
tf.constant([
            [[0, 1, 2, 3, 4],
             [5, 6, 7, 8, 9]],
            [[10, 11, 12, 13, 14],
             [15, 16, 17, 18, 19]],
            [[20, 21, 22, 23, 24],
             [25, 26, 27, 28, 29]],])

<tf.Tensor: id=6, shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])>

In [7]:
t = [

[3, 2, 1],

[6, 5, 4],

[9, 8, 7]

]

In [8]:
t

[[3, 2, 1], [6, 5, 4], [9, 8, 7]]

In [9]:
t[1][0]

6

In [10]:
tf.constant([

    [

         [2, 4, 4, 3] 

        ,[3, 2, 4, 5]

    ]

])

<tf.Tensor: id=8, shape=(1, 2, 4), dtype=int32, numpy=
array([[[2, 4, 4, 3],
        [3, 2, 4, 5]]])>

In [11]:
tensor = tf.constant([2, 14, 10, 12, 15, 3, 2, 5, 15, 78])

In [12]:
tensor

<tf.Tensor: id=10, shape=(10,), dtype=int32, numpy=array([ 2, 14, 10, 12, 15,  3,  2,  5, 15, 78])>

In [20]:
tensor[-1].numpy()

78

In [14]:
tensor[-1].numpy()

78

In [21]:
tensor[0].numpy()

2

In [22]:
tensor[0::2].numpy()

array([ 2, 10, 15,  2, 15])

In [23]:
tensor[:5].numpy()

array([ 2, 14, 10, 12, 15])

In [18]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])

In [19]:
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


In [ ]:
#pip install tensorflow --upgrade
!conda update tensorflow